services:
  xadmin-client-build:
    container_name: xadmin-client-build
    image: xadmin-node:22.10.0-alpine
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - sh
      - -c
      - pnpm install --frozen-lockfile && pnpm build
